version: "3.9"

# TODO migrator service
services:
  server:
    build: ./
    command: ./main
    ports:
      - 8089:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5555:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5