CREATE TABLE transaction (
    transaction_id SERIAL PRIMARY KEY,
    request_id INT,
    terminal_id INT,
    partner_object_id INT,
    amount_total DECIMAL(12, 2),
    amount_original DECIMAL(12, 2),
    commission_ps DECIMAL(12, 2),
    commission_client DECIMAL(12, 2),
    commission_provider DECIMAL(12, 2),
    date_input TIMESTAMP,
    date_post TIMESTAMP,
    status VARCHAR(256),
    payment_type VARCHAR(256),
    payment_number CHAR(10),
    service_id INT,
    service TEXT,
    payee_id INT,
    payee_name TEXT,
    payee_bank_mfo char(6),
    payee_bank_account CHAR(17),
    payment_narrative TEXT
);
