port: "8080"

db:
  username: "postgres"
  # change host to service name in docker-compose file
  host: "db"
  # change port to default in docker container
  port: "5432"
  name: "evo-test"
  password: "postgres"
