basePath: /
host: localhost:8089
info:
  contact: {}
  description: API Server Evo Test Task
  title: Evo Test Task
  version: "1.0"
paths:
  /api/transaction:
    get:
      consumes:
      - application/json
      description: get transaction
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Gets a transaction
      tags:
      - api
swagger: "2.0"
